### ISSUE TITLE
Pull out wallpaper colors on android 13 and android 12 easter egg

### ISSUE THREAD

**Issue by Seandylan123** [hushenghao/AndroidEasterEggs#10]
Just like google easter egg from android 12/13 it will have to pull out wallpaper color on android 8.1 and higher

**Comment by Seandylan123** [comment]
Also for the widget

**Comment by hushenghao** [comment]
Android12 and 13 are not wallpaper colors, but dynamic colors. They can only be used on most devices on Android 12 and above.

**Comment by hushenghao** [comment]
This project is designed to organize and compatible without excessive changes to the behavior of the system egg. If you want to contribute to the current project, I would like to welcome you.
