### ISSUE TITLE
[Bug] The background color of the bottom dialog is abnormal in versions earlier than Android 12

### ISSUE THREAD

**Issue by Jesse205** [hushenghao/AndroidEasterEggs#112]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

2.2.0

### Bug description / Bug 描述

![Screenshot_20231125_182402_com.dede.android_eggs.jpg](https://github.com/hushenghao/AndroidEasterEggs/assets/51242302/6b4a497c-a77c-44a8-b68c-d1d810f69114)

看图

### Expected behavior / 预期行为

对话框背景为淡绿色，是主题色

### Actual behavior / 实际行为

对话框背景为淡紫色

### Steps to reproduce / 复现步骤

1. 点击设置按钮

### UI / OS

HarmonyOS 3.0

### Android Version / Android 版本

10

### Additional info / 额外信息

LogFox的解决方案：https://github.com/F0x1d/LogFox/blob/master/app/src/main/res/values/styles.xml

**Comment by hushenghao** [comment]
Pic cant preview

**Comment by Jesse205** [comment]
> Pic cant preview

I'm very sorry, I have already resolved this problem.
