### ISSUE TITLE
[BUG] New Compose Refactor causes error on first start

### ISSUE THREAD

**Issue by user0-tb** [hushenghao/AndroidEasterEggs#116]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

2.2.2

### Bug description / Bug 描述

![Screenshot_20231128_171526_com dede android_eggs](https://github.com/hushenghao/AndroidEasterEggs/assets/104380885/8cf385b8-996b-439f-ad97-c5926dce7621)

### Expected behavior / 预期行为

An Button to close should be available 

### Actual behavior / 实际行为

No close icon is available 

### Steps to reproduce / 复现步骤

Uninstall and reinstall the app, than open it

### UI / OS

Emui 12

### Android Version / Android 版本

10

**Comment by hushenghao** [comment]
This is caused by the length of the words, which I did not consider perfectly. 
Switching to other languages can temporarily solve it.

**Comment by user0-tb** [comment]
![Screenshot_20231129_061351_com dede android_eggs](https://github.com/hushenghao/AndroidEasterEggs/assets/104380885/c00c0028-1f68-44a3-a2ce-d4d56a880d5b)
Now it's working fine.
