### ISSUE TITLE
NEKO does not work correctly on MIUI 12 and MIUI 13. 

### ISSUE THREAD

**Issue by Zibri** [hushenghao/AndroidEasterEggs#12]
NEKO does not work correctly on MIUI 12 and MIUI 13. 
Waterbowl can't be filled and crashes constantly.
Also, only the same cat comes.. not more as in my other phones.

**Comment by hushenghao** [comment]
MIUI has changed the system features, and it seems that it is not compatible with it.

**Comment by Zibri** [comment]
> The latest version has fixed the problem of cat refreshing and avoiding repeating one. [CatRandom.kt](https://github.com/hushenghao/AndroidEasterEggs/blob/718e9dae5469584a49631ed3e0bddd2efd8e71fb/basic/src/main/java/com/dede/basic/CatRandom.kt)
> 
> MIUI has modified a system feature that makes Waterbowl not work, but Waterbowl does not affect your cat's refresh chance

Then make it compatible! It's not that difficult!

**Comment by hushenghao** [comment]
If you're interested, you can try it

**Comment by hushenghao** [comment]
> > The latest version has fixed the problem of cat refreshing and avoiding repeating one. [CatRandom.kt](https://github.com/hushenghao/AndroidEasterEggs/blob/718e9dae5469584a49631ed3e0bddd2efd8e71fb/basic/src/main/java/com/dede/basic/CatRandom.kt)
> > MIUI has modified a system feature that makes Waterbowl not work, but Waterbowl does not affect your cat's refresh chance
> 
> Then make it compatible! It's not that difficult!

If you're interested, you can try it
