### ISSUE TITLE
Do you mind if I write a request to be added to F-Droid?

### ISSUE THREAD

**Issue by Artem13327** [hushenghao/AndroidEasterEggs#14]

**Comment by hushenghao** [comment]
Yes you can do this, also add F-Droid link to README by pull reuqest.

**Comment by hushenghao** [comment]
Today I handled the request to add to F-Droid by myself, thanks for your advice

**Comment by hushenghao** [comment]
> @hushenghao please fill it out then. It is not necessary to fill in everything. This data will be public
> 
> AuthorName: AuthorEmail: AuthorWebSite: WebSite: IssueTracker: Donate: Bitcoin: LiberaPay: AutoName:

AuthorName: Hu Shenghao
AuthorEmail: dede.hu@qq.com
AuthorWebSite:
WebSite: https://github.com/hushenghao/AndroidEasterEggs
IssueTracker: https://github.com/hushenghao/AndroidEasterEggs/issues
Donate: https://paypal.me/dede2233
Bitcoin:
LiberaPay:
AutoName:

Is this information OK?

**Comment by hushenghao** [comment]
> @hushenghao now could you create the metadata according to this instruction https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/

I have just been infected with COVID-19 and it may take a while to add this information

**Comment by hushenghao** [comment]
> @hushenghao Please add these changes to the master branch. I understand that the code from the master branch should be used

Merged

**Comment by hushenghao** [comment]
> @hushenghao please tell me the name of the app to use

Easter Eggs

You can find this information in the code repository.

**Comment by hushenghao** [comment]
> Please select a category https://gitlab.com/fdroid/fdroiddata/blob/master/stats/categories.txt

I think it belongs in those categories.
System 529
Games 376
Graphics 56

**Comment by hushenghao** [comment]
Does it take so long to be included for the first time?

**Comment by hushenghao** [comment]
Created fdroiddata MR 🎉

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13250
