### ISSUE TITLE
[Enhancment] Change settings to menu

### ISSUE THREAD

**Issue by inson1** [hushenghao/AndroidEasterEggs#142]
I hate that in About section is part of settings and functionality, it isnt user friendly

I would fix it by replacing settings with menu. 
In that menu would be Timeline, Package Manager, Settings, (About (It would be better to move it there too imho)).
In that order.

Alternatives
Or at least please add another line in About section for Timeline, Package Manager

PS If you dont like the idea please move it to discussion

**Comment by hushenghao** [comment]
I'm working on this

**Comment by hushenghao** [comment]
Optimize Setting prefs, move 'Timeline and Package Manager to More Settings
ref: https://github.com/hushenghao/AndroidEasterEggs/pull/148
