### ISSUE TITLE
Adding a language 

### ISSUE THREAD

**Issue by Maha-Rajan** [hushenghao/AndroidEasterEggs#159]
Hello, I would like to provide translation in my native language Tamil, it has 90M native speakers. I could not see my language in Crowdin. How do I add my language for translation?

**Comment by hushenghao** [comment]
I have added Tamil to Crowdin, looking forward to your contribution!
https://crowdin.com/project/easter-eggs/ta

**Comment by Maha-Rajan** [comment]
Done. Hope the translations get approved.
