### ISSUE TITLE
Fix menu items

### ISSUE THREAD

**Issue by LoryPelli** [hushenghao/AndroidEasterEggs#16]
It remains selected for example if we click a link and we close it

**Comment by hushenghao** [comment]
The selected status of item is not restored when clicked, which is the default feature. 

This problem is a low priority to fix

https://m3.material.io/components/navigation-drawer/overview

**Comment by LoryPelli** [comment]
> The selected status of item is not restored when clicked, which is the default feature. 
> 
> 
> 
> This problem is a low priority to fix
> 
> 
> 
> https://m3.material.io/components/navigation-drawer/overview

I participated while my friend was developing an app with Material 3 so ik how it work

**Comment by hushenghao** [comment]
Fixed
https://github.com/hushenghao/AndroidEasterEggs/commit/20a72bb2cc1eb9cfff2192e0c6468e94183de2c4

**Comment by LoryPelli** [comment]
> Fixed [20a72bb](https://github.com/hushenghao/AndroidEasterEggs/commit/20a72bb2cc1eb9cfff2192e0c6468e94183de2c4)

When will this be released?

**Comment by hushenghao** [comment]
> > Fixed [20a72bb](https://github.com/hushenghao/AndroidEasterEggs/commit/20a72bb2cc1eb9cfff2192e0c6468e94183de2c4)
> 
> When will this be released?

Soon, maybe this weekend
