### ISSUE TITLE
[BUG] android 6 彩蛋内存泄漏; There is a memory leak in the android M easter egg

### ISSUE THREAD

**Issue by k3x1n** [hushenghao/AndroidEasterEggs#164]
The variable i needs to be reassigned here, otherwise it will cause a memory leak.
https://github.com/hushenghao/AndroidEasterEggs/blob/ebd6001bd8c3edfbed7828dc44fe5cf7b3a913fc/eggs/Marshmallow/src/main/java/com/android_m/egg/MLand.java#L746

Reference:
[Bilibili: 越玩越卡，存在将近10年的安卓彩蛋内存泄露](https://www.bilibili.com/video/BV13m411973p)

不清楚google是否还在意android6的彩蛋游戏, 因此选择了向这个GooglePlay上的彩蛋项目报告这个小问题~

**Comment by hushenghao** [comment]
Fixed: 9db71c4a75c82b8546743d0f31439ea9e267e4cc
