### ISSUE TITLE
Icon Quiz shown on top of the app's ui

### ISSUE THREAD

**Issue by pisoj** [hushenghao/AndroidEasterEggs#165]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.3.1

### Bug description / Bug 描述

When activating the game of Android's 10 easter egg it shows on top of the **app's ui** instead of on top of the **wallpaper**. However, it only happens with _Retain recent Egg tasks_ turned off (which it the default). When creating a **new task** for every easter egg (like it was in pre 2.3.0) it acts as normal displaying on top of the users wallpaper.

### Expected behavior / 预期行为

Show the easter egg on top of the wallpaper.

### Actual behavior / 实际行为

Its shown on top of the apps ui.

### Steps to reproduce / 复现步骤

1. Open the app
2. Select Android 10's easter egg
3. Activate the game

### UI / OS

[Havoc-OS](https://havoc-os.com/)/Vanilla android

### Android Version / Android 版本

10

### Additional info / 额外信息

![Screenshot_20240204-140058](https://github.com/hushenghao/AndroidEasterEggs/assets/87895700/47bf5b2e-8584-402d-b5e6-4807f3efd35b)

**Comment by hushenghao** [comment]
Unbelievable, it only appears on Android 10 devices, but I will fix it

**Comment by hushenghao** [comment]
Fixd: 2fa8fb9f71c9525daa5e6fad8206c2cfba381ae4
