### ISSUE TITLE
Android 14 QPR3 Beta 1

### ISSUE THREAD

**Issue by qgmzmy** [hushenghao/AndroidEasterEggs#169]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。

### Enhancement propose / 改进目的

添加 Android 14 QPR3 Beta 1 中的倒三角彩蛋

### Solution / 解决方案

添加 Android 14 QPR3 Beta 1 中的倒三角彩蛋或忽略

### Additional info / 额外信息

https://9to5google.com/2024/02/07/android-14-qpr3-beta-1-easter-egg/

**Comment by hushenghao** [comment]
I didn't find a commit for QPR3 Beta 1, maybe it doesn't have a commit record.
https://github.com/aosp-mirror/platform_frameworks_base

**Comment by hushenghao** [comment]
I found this version of the egg in the emulator of VanillaIceCream Preview (Android 15 Developer Preivew), but it doesn't have any differences other than a different logo shape, so I wouldn't consider adding it.
![image](https://github.com/hushenghao/AndroidEasterEggs/assets/28776451/63e1b359-6d9a-404a-996f-ed11c4d036ab)

**Comment by qgmzmy** [comment]
👌

**Comment by hushenghao** [comment]
Add random logo on Android U
ref: https://github.com/hushenghao/AndroidEasterEggs/commit/7e5d340c0ae0bca446b1dacb2a6269085f0b5060
