### ISSUE TITLE
[FR]  Android 15 developer previews out

### ISSUE THREAD

**Issue by Danibrit1159** [hushenghao/AndroidEasterEggs#173]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。

### Enhancement propose / 改进目的

Android 15 developer preview is out. That means that a new Easter egg needs to be added

**Comment by hushenghao** [comment]
It's too early, the eggs will only be released on Release Preview

**Comment by Danibrit1159** [comment]
Ok

**Comment by hushenghao** [comment]
> Ok

Preview versions are usually released in August or September.

**Comment by The-ProGrammer66** [comment]
Plus, the current Android 15 easter egg is the same as 14, just with the circle in the logo being an upside-down triangle

**Comment by mounir47728** [comment]
It double thé easter egg like lolipop and marchmelo 
And 12 and 13

**Comment by pacjo** [comment]
[A wild Android 15 Easter egg appeared!](https://t.me/google_nws/4131)

**Comment by hushenghao** [comment]
The introduction of **Compose** has made decompilation more difficult, and I can't decompilate **Android 15 Easter Egg** 😭

**Comment by The-ProGrammer66** [comment]
> The introduction of **Compose** has made decompilation more difficult, and I can't decompilate **Android 15 Easter Egg** 😭

What do you mean?

**Comment by hushenghao** [comment]
> > The introduction of **Compose** has made decompilation more difficult, and I can't decompilate **Android 15 Easter Egg** 😭
> 
> What do you mean the introduction of Compose?

The source code for Android 15 has not been released yet, so I need to decompile the Easter egg for Android 15 for the time being

**Comment by user0-07161** [comment]
Dang it.

**Comment by hushenghao** [comment]
1452c000bca38449365b2747e29b762ac2f71491

v3.0.0 is coming
