### ISSUE TITLE
Seperate App for TRexRun3D

### ISSUE THREAD

**Issue by WreckingBANG** [hushenghao/AndroidEasterEggs#19]
I really loved to play TRexRun3D in my Spare Time. I really miss it. Could you please do a seperate App for it?

**Comment by hushenghao** [comment]
I will release it as soon as possible.

**Comment by WreckingBANG** [comment]
Thank You

**Comment by LoryPelli** [comment]
> I will release it as soon as possible.

Will it include improvements like user account, leaderboard?
