### ISSUE TITLE
Language setting and icon shape setting don't work

### ISSUE THREAD

**Issue by LoryPelli** [hushenghao/AndroidEasterEggs#20]
The first makes the app completely crash and the second doesn't change anything if you change it

**Comment by hushenghao** [comment]
The **icon shape** setting causes the application to restart.
**Language** setting Android T and above are required

Could you please provide your device model and system version if Icon Shpae does not work

**Comment by LoryPelli** [comment]
> The **icon shape** setting causes the application to restart. **Language** setting Android T and above are required
> 
> Could you please provide your device model and system version if Icon Shpae does not work

I have android 13, Xiaomi 11 Lite 5G NE, 8GB ram, 128GB internal memory

**Comment by hushenghao** [comment]
> 

I tested it on Xiaomi devices, miui needs to be adapted, it will be released soon

**Comment by LoryPelli** [comment]
> > 
> 
> I tested it on Xiaomi devices, miui needs to be adapted, it will be released soon

Ok, what about the language setting?

**Comment by hushenghao** [comment]
> > > 
> > 
> > 
> > I tested it on Xiaomi devices, miui needs to be adapted, it will be released soon
> 
> Ok, what about the language setting?

This is a MIUI problem, I can only fix it to keep the app from crashing

**Comment by hushenghao** [comment]
The **Icon Shape** setting has been fixed. You can download the latest [Beta](https://www.pgyer.com/eggs) to try it out.
https://github.com/hushenghao/AndroidEasterEggs/commit/f91c6e54e2ae0c5f2b21ee23b3faf5be82f71af1
