### ISSUE TITLE
[BUG] 平板端无法关闭侧滑

### ISSUE THREAD

**Issue by Jesse205** [hushenghao/AndroidEasterEggs#211]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.4.0

### Bug description / Bug 描述

![Screenshot_20240314_091800_com dede android_eggs](https://github.com/hushenghao/AndroidEasterEggs/assets/51242302/09f02370-3128-416b-88df-07e4e2f5c9d7)

### Expected behavior / 预期行为

侧滑可以关闭，或者常驻但不挡内容

### Actual behavior / 实际行为

侧滑无法关闭，内容被挡

### Steps to reproduce / 复现步骤

1.，打开应用

### UI / OS

harmony os

### Android Version / Android 版本

12

**Comment by hushenghao** [comment]
点击返回按钮可以关闭吗

**Comment by Jesse205** [comment]
也不可以

**Comment by hushenghao** [comment]
Fixed
