### ISSUE TITLE
Froyo not avaliable [BUG] 

### ISSUE THREAD

**Issue by MouseyRain98972** [hushenghao/AndroidEasterEggs#213]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [x] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.4.1

### Bug description / Bug 描述

It will not let me do froyo easter egg

### Expected behavior / 预期行为

It letting me do froyo easter egg

### Actual behavior / 实际行为

Showed the logo, I think 🐱, 🚫, and 🥚

### Steps to reproduce / 复现步骤

Open the app, pick froyo.

### UI / OS

OneUI 6.0

### Android Version / Android 版本

14

**Comment by hushenghao** [comment]
🤖🚫🥚
This Android version didn't have eggs before
