### ISSUE TITLE
Add an option for `FIXME` in Android 14 Easter eggs 

### ISSUE THREAD

**Issue by RocketMaDev** [hushenghao/AndroidEasterEggs#214]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。

### Enhancement propose / 改进目的

Reverse the switch `DYNAMIC_ZOOM` could make the space game more fun as people can easily find their ultimate targets.

### Solution / 解决方案

Just modify the boolean const `DYNAMIC_ZOOM` in `/eggs/UpsideDownCake/src/main/java/com/android_u/egg/landroid/MainActivity.kt @ line 103` from `false` to `true`.

Or add a switch in app settings to decide whether the `DYNAMIC_ZOOM` is on.

**Comment by hushenghao** [comment]
The `DYNAMIC_ZOOM` field is more for debugging purposes, and a similar field exists in almost all eggs, so I'm not going to add this switch configuration

**Comment by hushenghao** [comment]
Do you have any questions?

**Comment by RocketMaDev** [comment]
Plz watch this video if you haven't watched it: [修改代码后才看懂Android14彩蛋的玩法：探索宇宙，降落到恒星周围的天体上-哔哩哔哩](https://b23.tv/VuvpGwh)

I searched `FIXME` in global scope, and `DYNAMIC_ZOOM` is one of the two. In my opinion, that may indicate reversing the `DYNAMIC_ZOOM` is a necessity. And according to the video, the visual effects is better. So I still suggest reversing the switch.

**Comment by hushenghao** [comment]
虽然实现它很简单，但是缩放比例是根据最近的星球计算的，最小缩放比例下甚至都找不到飞船的位置。
所以我不会接受这部分修改。
彩蛋的目的是探索，而不是为了完成目标。
