### ISSUE TITLE
Trying to uninstall the app crashes package installer

### ISSUE THREAD

**Issue by azuziii** [hushenghao/AndroidEasterEggs#24]
![SmartSelect_20230624_121405_Gallery](https://github.com/hushenghao/AndroidEasterEggs/assets/136205858/1dd45841-d2c3-4406-9e13-9dad76cf9a73)
I tried all possible ways to uninstall it but same problem, using a third party apps crashes it too.

**Comment by azuziii** [comment]
I'm on android 13

**Comment by hushenghao** [comment]
It's the crash of your ROM's package manager.
try `adb uninstall com.dede.android_eggs`
There is no other way for you to provide feedback to your device manufacturer

**Comment by Parmjot-Singh** [comment]
It only happens with this app, how is this our fault? I've installed from F-Droid, and experience the same behaviour.

**Comment by hushenghao** [comment]
Update this Apk to uninstall Easter Eggs.
[uninstall_easter_eggs_9.9.9_10000-release.apk](https://github.com/hushenghao/AndroidEasterEggs/blob/master/uninstall/uninstall_easter_eggs_9.9.9_10000-release.apk)

Read this [document](https://github.com/hushenghao/AndroidEasterEggs/blob/master/uninstall/README.md) to learn more

**Comment by Parmjot-Singh** [comment]
Thank you, it is fixed now
