### ISSUE TITLE
Android 14 Beta 4 New Easter Egg! 

### ISSUE THREAD

**Issue by NikSavchenk0** [hushenghao/AndroidEasterEggs#25]
So add new easter egg from Android 14 Beta 4.
![20230712_070232](https://github.com/hushenghao/AndroidEasterEggs/assets/58150480/d6c9fb66-0e5b-42ef-b6fb-768fe3ef577f)

**Comment by hushenghao** [comment]
v1.9.5 has been released, but the decompiled version does not yet support all features.

**Comment by NikSavchenk0** [comment]
decompiled easteregg14.apk from tg linuxct: https://drive.google.com/file/d/1arLBcDYkcSFN0j0FVHqkq4SQV-TYV42a/view?usp=sharing

**Comment by hushenghao** [comment]
I've tried decompiling 14 Easter Egg for the Android 14 Beta 4 release, but there's no way to make it compatible until AOSP releases the source code.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hushenghao/AndroidEasterEggs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月15日(星期六) 上午10:14
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hushenghao/AndroidEasterEggs] Android 14 Beta 4 New Easter Egg!  (Issue #25)





 
decompiled easteregg14.apk from tg linuxct: https://drive.google.com/file/d/1arLBcDYkcSFN0j0FVHqkq4SQV-TYV42a/view?usp=sharing
