### ISSUE TITLE
add u easter egg

### ISSUE THREAD

**Issue by Nilsu11** [hushenghao/AndroidEasterEggs#27]
I decompiled the u easter egg and uploaded the outcome here: https://github.com/Nilsu11/u-easter-egg-zip

Please add the u easter egg functionality. Thanks in advance.

**Comment by hushenghao** [comment]
JADX decompiled code, to run it, is usually impossible. Recently, I have also received many enthusiastic friends to provide Easter Egg.apk or decompiled code, thank you very much, but I have tried these schemes, at this stage is basically impossible to integrate into the App.
