### ISSUE TITLE
[FR] Rocket Launcher for Android 4.0

### ISSUE THREAD

**Issue by Starcr0ss** [hushenghao/AndroidEasterEggs#286]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。

### Enhancement propose / 改进目的

Hidden within the activities for the Android 4.0 Launcher was an entry called "Rocket Launcher" that would show a user's apps flying at them in a futuristic, space-like way. 
Here is a Chinese [article] (https://juggly.cn/archives/47483.html) that explains this Easter egg.
There is also a [video](https://www.youtube.com/watch?v=8ILnUmHVNtc) showing it in action.

**Comment by hushenghao** [comment]
Rocket Launcher doesn't seem to be a system egg, it's a launcher egg, but I'll consider adding it.
I will try to find the source code and try to recompile it

**Comment by hushenghao** [comment]
https://juggly.cn/archives/47483.html
This is a Japanese article. I don't like it.

**Comment by hushenghao** [comment]
I have compiled RocketLuncher successfully, I don't think it should be added to android system Egg, I haven't found out how to place it yet.

**Comment by GitPio** [comment]
![Uploading IMG_20240716_212938-1.jpg…]()

**Comment by dsandler** [comment]
I'd suggest porting it back to a Dream since it was intended to be [Launcher2's hidden screensaver](https://android.googlesource.com/platform/packages/apps/Launcher2/+/4e1cd23a51f1d83c1fe5d3eed536641087671db7).

**Comment by hushenghao** [comment]
> I'd suggest porting it back to a Dream since it was intended to be [Launcher2's hidden screensaver](https://android.googlesource.com/platform/packages/apps/Launcher2/+/4e1cd23a51f1d83c1fe5d3eed536641087671db7).

That sounds good.

**Comment by hushenghao** [comment]
https://github.com/hushenghao/AndroidEasterEggs/pull/446

**Comment by Monday1908** [comment]
> ### Checklist / 检查清单
> * [x]  No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
> * [x]  This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。
> 
> ### Enhancement propose / 改进目的
> Hidden within the activities for the Android 4.0 Launcher was an entry called "Rocket Launcher" that would show a user's apps flying at them in a futuristic, space-like way. Here is a Chinese [article] (https://juggly.cn/archives/47483.html) that explains this Easter egg. There is also a [video](https://www.youtube.com/watch?v=8ILnUmHVNtc) showing it in action.
> 
> ### Solution / 解决方案
> _No response_
> 
> ### Additional info / 额外信息
> _No response_
