### ISSUE TITLE
widgets of easter eggs

### ISSUE THREAD

**Issue by RustoMCSpit** [hushenghao/AndroidEasterEggs#29]

**Comment by hushenghao** [comment]
what issue?

**Comment by RustoMCSpit** [comment]
> what issue?

like, make the easter eggs function as widgets

**Comment by hushenghao** [comment]
> > what issue?
> 
> like, make the easter eggs function as widgets
Understood

**Comment by simsimient1** [comment]
> > > what issue?
> > 
> > 
> > like, make the easter eggs function as widgets
> 
> Understood

widget eggs lol

**Comment by hushenghao** [comment]
<img width="400" alt="image" src="https://github.com/hushenghao/AndroidEasterEggs/assets/28776451/4afa9d0e-bb17-4aad-8594-e7a204eb00bd">

**Comment by hushenghao** [comment]
> > <img alt="image" width="400" src="https://user-images.githubusercontent.com/28776451/259683628-4afa9d0e-bb17-4aad-8594-e7a204eb00bd.png">
> 
> ?

This is Easter Eggs Analog clock widget

**Comment by RustoMCSpit** [comment]
> > > <img alt="image" width="400" src="https://user-images.githubusercontent.com/28776451/259683628-4afa9d0e-bb17-4aad-8594-e7a204eb00bd.png">
> > 
> > 
> > ?
> 
> This is Easter Eggs Analog clock widget

can you use it like a regular widget?

**Comment by hushenghao** [comment]
> > > > <img alt="image" width="400" src="https://user-images.githubusercontent.com/28776451/259683628-4afa9d0e-bb17-4aad-8594-e7a204eb00bd.png">
> > > 
> > > 
> > > ?
> > 
> > This is Easter Eggs Analog clock widget
> 
> can you use it like a regular widget?

 absolutely

**Comment by hushenghao** [comment]
> 
> can you show me you using it like a regular wifget as i cant see the option to use it like a widget

![image](https://github.com/hushenghao/AndroidEasterEggs/assets/28776451/2f9b07cc-feec-4f47-8f2e-92aa547cb6a7)
Download bate https://www.pgyer.com/eggs

**Comment by simsimient1** [comment]
please don't qwess, it game Team Run.
