### ISSUE TITLE
Disable upgrade check

### ISSUE THREAD

**Issue by shuvashish76** [hushenghao/AndroidEasterEggs#317]
v2.6.0 added "App upgrade check" which is on by default and no option to disable it.
Connects to `api.github.com`

[Tracking](https://f-droid.org/en/docs/Anti-Features/#Tracking) AF is required for F-Droid/IzzyOnDroid as it checks updates without the user knowledge or permission.

Request to completely disable internet permission or make this feature opt-in i.e. disabled by default.

**Comment by hushenghao** [comment]
I will remove it, it is not necessary
