### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [hushenghao/AndroidEasterEggs#322]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

2.6.2

### Bug description / Bug 描述

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7402993577#L941

ref: https://github.com/hushenghao/AndroidEasterEggs/commit/7aac6a23f90f4043fb476a2c5a18d2bb00b2af0f#diff-5625e3601fa0ad3a6a2824239e5a2fde71c149597d31394f9224a08c24be7b9dR14

that maven repo is not on the trusted list: https://gitlab.com/fdroid/fdroidserver/-/blob/df97ebe05298b6c0261d2dfbc1c2dd05687cfc7c/fdroidserver/scanner.py#L457-L475

### Expected behavior / 预期行为

-

### Actual behavior / 实际行为

-

### UI / OS

-

### Android Version / Android 版本

-

**Comment by hushenghao** [comment]
Please pause the release of 2.6.2. 
We need to wait for R8 publish to Google repo to fix this

**Comment by hushenghao** [comment]
commit: 99a538a886352fd1afcc799e0b81f6c6a95202f3

AGP 8.5.2 update r8 to 8.5.35
