### ISSUE TITLE
[FR] Make the clock widget a shortcut wheel too

### ISSUE THREAD

**Issue by Hanifinio** [hushenghao/AndroidEasterEggs#348]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。

### Enhancement propose / 改进目的

The clock widget has all of the icons of the Android versions outside its ring. It would be cool if you could press on an icon and it took you to its corresponding activity (Easter egg).

### Solution / 解决方案

I'm not experienced in how these things work but I think you should just be able to make the icons their own buttons the do their own thing (the thing being the above).

**Comment by hushenghao** [comment]
I don't think this is a good idea, as the buttons for making widgets would be too small, and not all times have corresponding Easter eggs, such as one o'clock.

**Comment by hushenghao** [comment]
How about opening the app when clicking on the widget and changing it to open the Easter egg corresponding to the system version based on the current time?

**Comment by Hanifinio** [comment]
That would still be pretty cool. Sure

**Comment by hushenghao** [comment]
Finished https://github.com/hushenghao/AndroidEasterEggs/commit/cebc6a87218a945ddec54414ba404816ea9f10a9

**Comment by ruben0416** [comment]
> Finished https://github.com/hushenghao/AndroidEasterEggs/commit/cebc6a87218a945ddec54414ba404816ea9f10a9
