### ISSUE TITLE
[BUG] 安卓12-15在深色模式下没有对应彩蛋的深色模式效果

### ISSUE THREAD

**Issue by JYN2018X** [hushenghao/AndroidEasterEggs#386]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

3.0.1

### Bug description / Bug 描述

当你安卓手机在深色模式时，你在选择安卓12-15系统的彩蛋时没有深色模式的效果，但是系统设置里面就有，麻烦加一下，安卓10-11都已经加上去了

### Expected behavior / 预期行为

深色模式时安卓12-15会显示深色效果的彩蛋

### Actual behavior / 实际行为

深色模式时安卓12-15没有深色效果而是浅色模式下的效果

### Steps to reproduce / 复现步骤

1.切换为深色模式
2.打开彩蛋软件，选择安卓12-15之间的彩蛋
3.发现和设置里面设置的彩蛋不一样，一个浅色一个深色

### UI / OS

OriginOS 4

### Android Version / Android 版本

14

### Additional info / 额外信息

希望完善好，加上深色模式的彩蛋

**Comment by hushenghao** [comment]
有截图吗，我查看了Android 12-15的系统彩蛋，从代码和行为上都是没有实现深色模式的

|系统版本|截图|
|---|---|
|Andorid 12|<img width="200" src="https://github.com/user-attachments/assets/01933d20-4c56-4095-b3f5-0b7197792b34"/> <img width="200" src="https://github.com/user-attachments/assets/dd8cea06-ea7b-4412-9d86-5502e96c35e3"/> <img width="200" src="https://github.com/user-attachments/assets/7514551b-dcee-48c5-ae46-9506507db9c8"/>|
|Android 13|<img width="200" src="https://github.com/user-attachments/assets/fd10a5c6-0d32-4eba-8c83-7bfc95e50cc7"/> <img width="200" src="https://github.com/user-attachments/assets/870f88af-2b35-4f19-ac53-76e7b54fe07c"/> <img width="200" src="https://github.com/user-attachments/assets/0098761e-f43b-449e-bd96-6690965631f8"/>|
|Android 14|<img width="200" src="https://github.com/user-attachments/assets/dc80ebb9-3e7a-48bd-a3ef-5702ce079706"/> <img width="200" src="https://github.com/user-attachments/assets/f00cee2f-98a4-498e-89ff-c1e4757adf2f"/> <img width="200" src="https://github.com/user-attachments/assets/b9307b81-c455-48f3-a0ae-da693ffb1227"/>|
|Android 15|<img width="200" src="https://github.com/user-attachments/assets/9b785a4e-7c8a-4645-8d79-aacda879f351"/> <img width="200" src="https://github.com/user-attachments/assets/68dae3a7-8b16-41c0-a282-82004f1cdb3d"/> <img width="200" src="https://github.com/user-attachments/assets/4348a33f-d824-40b0-8573-0e39de6b7111"/>|

**Comment by JYN2018X** [comment]
![Screenshot_20240929_161737](https://github.com/user-attachments/assets/f78f6d17-30c3-4bfe-9191-602a5efb1f37)
这个是我在安卓14的上面的，不过我安卓12，13，15的设备都没有，只能看看其他人的了

**Comment by JYN2018X** [comment]
而且在深色模式下打开彩蛋软件的时候也可以看到有深色模式的效果

**Comment by JYN2018X** [comment]
我在其他的安卓设备上就有了，你那个谷歌Pixel我好像不知道这个有没有

**Comment by hushenghao** [comment]
> <img width="200" src="https://private-user-images.githubusercontent.com/120889262/371837874-f78f6d17-30c3-4bfe-9191-602a5efb1f37.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTgzMzEsIm5iZiI6MTcyNzU5ODAzMSwicGF0aCI6Ii8xMjA4ODkyNjIvMzcxODM3ODc0LWY3OGY2ZDE3LTMwYzMtNGJmZS05MTkxLTYwMmE1ZWZiMWYzNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwODIwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWRkNTBhZTBkODE5ZTE0OGViM2VlMjhkY2ZmMDRmY2U1ZWZjZTk5NzhhNDQ0NzFjNmExZmE0NzJmMzA2ZTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sRRH5vLeEulBbYLm-inp-Pz2hDhLvqGqxMsFuopddK0" />这个是我在安卓14的上面的，不过我安卓12，13，15的设备都没有，只能看看其他人的了


我认为这是VIVO定制的深色模式，对一部分高亮度的颜色进行了反转，这种方案在国产定制系统上很常见，可以在系统的设置里对系统彩蛋app添加白名单再查看，这是魅族的深色模式设置：
<img width="422" alt="image" src="https://github.com/user-attachments/assets/7cfbd3ea-ca2c-4ba7-a47d-d612cd870cf2">

**Comment by JYN2018X** [comment]
我这个vivo手机上面没有只有一个软件

**Comment by JYN2018X** [comment]
算了，这个可能是国产手机里面的深色模式反转导致的，这个算不能修复解决掉吧
