### ISSUE TITLE
[BUG] Fixing an Beta CI error for badge

### ISSUE THREAD

**Issue by HeySimSimi** [hushenghao/AndroidEasterEggs#392]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [ ] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

Shields Version of server-2024-09-25 (#10552)

### Bug description / Bug 描述

Fixed badge YML.

### Expected behavior / 预期行为

Fixed an badge YML error of GitHub Beta CI.

### Actual behavior / 实际行为

Fix workflows.

### Steps to reproduce / 复现步骤

1. Commit of f6d6aa1 a GitHub.
2. Simple badge.

### UI / OS

Etc

### Android Version / Android 版本

Nothing is slow

### Additional info / 额外信息

![Beta CI](https://camo.githubusercontent.com/45c4d503bce77b0044ab1da21e905b81b930347e80134fe3ddfeabf66bf6d457/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f616374696f6e732f776f726b666c6f772f7374617475732f68757368656e6768616f2f416e64726f6964456173746572456767732f6275696c64426574612e796d6c3f6c6f676f3d676974687562266c6162656c3d426574612532304349267374796c653d666c6174)

**Comment by HeySimSimi** [comment]
Before: ![Beta](https://camo.githubusercontent.com/45c4d503bce77b0044ab1da21e905b81b930347e80134fe3ddfeabf66bf6d457/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f616374696f6e732f776f726b666c6f772f7374617475732f68757368656e6768616f2f416e64726f6964456173746572456767732f6275696c64426574612e796d6c3f6c6f676f3d676974687562266c6162656c3d426574612532304349267374796c653d666c6174)

After: ![Pgyer](https://camo.githubusercontent.com/df9c96e115fe0a22438f644fea91cd82673007a0636c51663cebeb9ba44a3689/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f616374696f6e732f776f726b666c6f772f7374617475732f68757368656e6768616f2f416e64726f6964456173746572456767732f70677965722e796d6c3f6c6f676f3d676974687562266c6162656c3d50677965722532304349267374796c653d666c6174)

**Comment by hushenghao** [comment]
pgyer changed from beta to alpha track
