### ISSUE TITLE
Change Easter egg via xml

### ISSUE THREAD

**Issue by upintheairsheep** [hushenghao/AndroidEasterEggs#4]
<category android:name="com.android.internal.category.PLATLOGO" />

Makes an activity be default for the Easter egg after the logo is complete. You should make all Easter eggs and platlogos with this and try out opening the regular Easter egg

**Comment by porg13231** [comment]
Yes. Red velvet is not good all it is a knob.

**Comment by hushenghao** [comment]
This is not possible. Cat controls use the new features of android R, which can only be used on Android R and above.
