### ISSUE TITLE
Android 12 and android 13 dont have paint chips widget

### ISSUE THREAD

**Issue by Adam9859** [hushenghao/AndroidEasterEggs#419]
Add the widget  for android 12 and android 13 the widget looks like this in settings android 12 and android 13 have widget called paint chips
![c94i33556su71](https://github.com/user-attachments/assets/9ae868bb-07ae-4898-9d4f-7960f8fc56a9)
![Screenshot_20241110-115900_One UI Home](https://github.com/user-attachments/assets/9c92e9c8-b701-4fc9-8d33-da63b3451e8e)

**Comment by hushenghao** [comment]
Android 12 and 13 Paint Chips widgets require unlocking Easter egg before they can be added.
![Screenshot_20241111_093231](https://github.com/user-attachments/assets/56207415-68eb-4a4f-ad17-4ad8708d7209)
