### ISSUE TITLE
[FR] New! App freeze easter egg is available now [Opened]

### ISSUE THREAD

**Issue by NurMiApp** [hushenghao/AndroidEasterEggs#423]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。

### Enhancement propose / 改进目的

Easter Eggs freezing app for the aboutic is added. In Easter Eggs, or freeze was just apps still easter egg Landroid is freezer: Android 15 or Android 14. But it's not too late, was just AppControl special thanks?

This was for application freeze warned SD Maid SE issues closed: [#1462](https://github.com/d4rken-org/sdmaid-se/issues/1462)

**Comment by hushenghao** [comment]
SuperFreezZ just uses accessibility features to help you force stop unnecessary apps, I don't understand what I need to do.

**Comment by NurMiApp** [comment]
I am not supported was just SuperFreezZ liked that delay Android 12 not support. Of course simpled: Android 12

Made close issues in #423 foundation.

**Comment by hushenghao** [comment]
If you have any questions about SuperFreezZ, please move to the SuperFreezZ repository to submit your issue.

**Comment by NurMiApp** [comment]
> If you have any questions about SuperFreezZ, please move to the SuperFreezZ repository to submit your issue.

Yes, we are good.
