### ISSUE TITLE
Missing colors in android pie easter egg 

### ISSUE THREAD

**Issue by Adam9859** [hushenghao/AndroidEasterEggs#429]
Some colors don't have these in easter eggs pie 
![20241124_163609](https://github.com/user-attachments/assets/15cb8a79-c705-4751-a29b-b8b3a92f089e)
![20241124_163856](https://github.com/user-attachments/assets/a42f9aa5-7dd0-4fff-8d7e-371ab95abbd4)
![20241124_163914](https://github.com/user-attachments/assets/3d6cc729-e876-45b2-84d8-a1ac8d1e9369)
![20241124_165044](https://github.com/user-attachments/assets/05fd8829-fbfb-4800-af68-04a0f7c2b188)
![20241124_164146](https://github.com/user-attachments/assets/645e2bf8-77af-49a1-9664-df027887d85c)
![Screenshot_20241124-164736_Chrome](https://github.com/user-attachments/assets/fd23da55-f096-4252-b217-04299a2bbd7b)

**Comment by hushenghao** [comment]
The colors are random. No color is missing. It's just luck
