### ISSUE TITLE
Liberapay link on fdroid metadata

### ISSUE THREAD

**Issue by jindam-vani** [hushenghao/AndroidEasterEggs#51]
@hushenghao 
* **without your explicit consent** Liberapay link ```https://liberapay.com/Hu_Shenghao``` given in "Sponsor this project" on github was updated by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.dede.android_eggs.yml)
* Liberapay link updated in fdroid metadata will create link on fdroid client
* should i remove it?

**Comment by hushenghao** [comment]
I have seen the `fdroid metadata` updated last time and can keep it
