### ISSUE TITLE
Android 13 Not Vibrating 

### ISSUE THREAD

**Issue by user0-tb** [hushenghao/AndroidEasterEggs#52]
On Android 13 are some Easter eggs Not Vibrating.
I think only `<uses-permission android:name="android.permission.VIBRATE" />` needs to bei added to AndroidManifest.xml.

**Comment by hushenghao** [comment]
Vibration permissions have been added to the application, and not all vibrations require vibration permissions.
For example: [view.performHapticFeedback(HapticFeedbackConstants.XXX)](https://developer.android.google.cn/reference/kotlin/android/view/View?hl=en#performHapticFeedback(kotlin.Int))

* [HapticFeedbackConstants.LONG_PRESS](https://developer.android.google.cn/reference/kotlin/android/view/HapticFeedbackConstants?hl=en#long_press): The user has performed a long press on an object that is resulting in an action being performed.
* [HapticFeedbackConstants.CLOCK_TICK](https://developer.android.google.cn/reference/kotlin/android/view/HapticFeedbackConstants?hl=en#clock_tick): The user has pressed either an hour or minute tick of a Clock.
* ...

On Android 13 Easter egg, Used `HapticFeedbackConstants.CLOCK_TICK` and `HapticFeedbackConstants.LONG_PRESS` to trigger vibration, but `HapticFeedbackConstants. CLOCK_TICK ` vibration time and strength is shorter.

The absence of vibration feedback may be a limitation of the device, for example, the device is not equipped with a linear vibrator, but with a traditional eccentric vibrator, Or **disabled vibration feedback in system settings**.
