### ISSUE TITLE
11的彩蛋在部分定制ui无法正常使用

### ISSUE THREAD

**Issue by xiersa** [hushenghao/AndroidEasterEggs#6]
您好，安卓11的养猫彩蛋用到了设备控制器的功能。而这个功能在部分定制ui（如：miui）上会有一些问题，比如在miui上没法滑动加水。能否将这个加水的交互增加一下点击也可以加呢？

**Comment by porg13231** [comment]
Yeah. Samsung 1 ui not working on this.

**Comment by hushenghao** [comment]
This cannot be achieved. You can only hope that the system can fix this problem as soon as possible.
