### ISSUE TITLE
English translation of privacy policy

### ISSUE THREAD

**Issue by ivan-avalos** [hushenghao/AndroidEasterEggs#64]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v1.9.7

### Bug description / Bug 描述

Privacy policy is only in Chinese. Besides, why is there a privacy policy in the first place? Where is the app sending data to?

### Expected behavior / 预期行为

Privacy policy in English

### Actual behavior / 实际行为

Privacy policy only in Chinese

### UI / OS

Android

### Android Version / Android 版本

13

**Comment by hushenghao** [comment]
This is only in response to the demands of the Chinese app store, which does not collect any information and does not even have access to the Internet.
