### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by Unkrown6YT** [hushenghao/AndroidEasterEggs#81]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical feature request before. / 之前没有人提交过类似或相同的功能请求。
- [X] This suggestion does not depart from the original intention of Easter Eggs. / 这个建议不会背离 Easter Eggs 的初衷。

### Enhancement propose / 改进目的

Make Android 14 work on Easter Eggs app after Android 14 got launched

### Solution / 解决方案

The egg on Android 14(not code name) should be "Space"
The minimum api level in android 14 is 34(I guess)

**Comment by hushenghao** [comment]
I'll add the full Android 14 Easter Egg as soon as possible

**Comment by hushenghao** [comment]
Regarding the name "Space" of the android 14 easter egg, I don't know what the source of this information is. I didn't find an official explanation on the search engine.
