### ISSUE TITLE
[Bug] Android 8.0 与 Android 8.1 彩蛋反了

### ISSUE THREAD

**Issue by Jesse205** [hushenghao/AndroidEasterEggs#83]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.0.0

### Bug description / Bug 描述

Android 8.0 与 Android 8.1 彩蛋反了

### Expected behavior / 预期行为

-  Android 8.0为圆形菜单
- Android 8.1为奥利奥彩蛋

### Actual behavior / 实际行为

-  Android 8.0出现奥利奥彩蛋
- Android 8.1出现圆形彩蛋

### Steps to reproduce / 复现步骤

1. 点击Android 8.0彩蛋
2. 切换为Android8.1，点击彩蛋

### UI / OS

HarmonyOS

### Android Version / Android 版本

10

### Additional info / 额外信息

None

**Comment by hushenghao** [comment]
3Q

**Comment by simsimient1** [comment]
Hi @hushenghao is Android 8.0 & 8.1 toast "Oops, again octopus version!"

**Comment by hushenghao** [comment]
> Hi @hushenghao is Android 8.0 & 8.1 toast "Oops, again octopus version!"

In AOSP [android-8.0-r51](https://cs.android.com/android/platform/superproject/+/android-8.0.0_r51) branch: 
[PlatLogoActivity.java](https://cs.android.com/android/platform/superproject/+/android-8.0.0_r51:frameworks/base/core/java/com/android/internal/app/PlatLogoActivity.java)
[Ocquarium.java](https://cs.android.com/android/platform/superproject/+/android-8.0.0_r51:frameworks/base/packages/EasterEgg/src/com/android/egg/octo/Ocquarium.java)
I didn’t find any logic related to Toast. Can you tell me how you found out?

**Comment by simsimient1** [comment]
> I didn’t find any logic related to Toast. Can you tell me how you found out?

I am going Disable octopus dialog is "Crash for com.android.egg"
Really is Android 4.5 monochrome Easter Eggs V2.0.0 "Coffee Android"
- Add Android 4.5 monochrome "Coffee Android"
- Update welcome "Animation Coffee Android"
- Add crash log "com.android.egg"
- Bug Fix
Release V2.0.0
As Coffee Android update!

**Comment by hushenghao** [comment]
> I am going Disable octopus dialog is "Crash for com.android.egg" Really is Android 4.5 monochrome Easter Eggs V2.0.0 "Coffee Android"
> 
> * Add Android 4.5 monochrome "Coffee Android"
> * Update welcome "Animation Coffee Android"
> * Add crash log "com.android.egg"
> * Bug Fix
>   Release V2.0.0
>   As Coffee Android update!

I don’t understand what the question is. If possible, you can open a new issue for discussion.

**Comment by simsimient1** [comment]
> I don’t understand what the question is. If possible, you can open a new issue for discussion.

We have "Coffee Android" is Android Monochrome 4.5 developer preview

**Comment by hushenghao** [comment]
> We have "Coffee Android" is Android Monochrome 4.5 developer preview

Is it different from 4.4?

**Comment by hushenghao** [comment]
> We have "Coffee Android" is Android Monochrome 4.5 developer preview

You can provide the apk or source code for me to try to solve it, can contact me via email: dede.hu@qq.com

**Comment by user0-tb** [comment]
> > We have "Coffee Android" is Android Monochrome 4.5 developer preview
> 
> You can provide the apk or source code for me to try to solve it, can contact me via email: [dede.hu@qq.com](mailto:dede.hu@qq.com)

Take a look [here](https://github.com/aosp-mirror/platform_frameworks_base/tree/l-preview). It's the lollipop beta, that's maybe the 4.5 version.

**Comment by hushenghao** [comment]
> 
> Take a look [here](https://github.com/aosp-mirror/platform_frameworks_base/tree/l-preview). It's the lollipop beta, that's maybe the 4.5 version.

I'm sure it's not Android 4.5. 
As far as I know, Monochrome is just an Android 5-style icon pack, and Google will not develop Easter eggs specifically for a preview version.

**Comment by simsimient1** [comment]
> It's the lollipop beta, that's maybe the 4.5 version.

I am is Moonshine 4.5 Easter Eggs update v2.0.0 update :c
