### ISSUE TITLE
Suggestion: Android 10 Easter egg match with device theme

### ISSUE THREAD

**Issue by Danibrit1159** [hushenghao/AndroidEasterEggs#9]
![Screenshot_20220824-190224](https://user-images.githubusercontent.com/63423486/186538503-f40365a5-4728-4688-b565-f70642442654.png)
In The official Android 10 Easter egg. If you have a dark mode then the Easter egg will be in dark mode and if your theme is light the Android Easter egg will be in light mode. But in this app it will always be in light mode no matter if your phone is dark or not

It's not a bug, it's just a suggestion

**Comment by hushenghao** [comment]
Thank you for your suggestions. The next version will be repaired

**Comment by Danibrit1159** [comment]
Cool! Thank you for taking my suggestion
